### ISSUE TITLE
Add bootstrap modal on checkmate and stalemate.

### ISSUE THREAD

**Issue by radi-cho** [RSG-Group/Chess#1]

**Comment by retrixe** [comment]
Much needed. Also, stalemate.

**Comment by radi-cho** [comment]
![image](https://user-images.githubusercontent.com/12954909/33082395-5a355c3a-cee5-11e7-9e60-20907c94cde2.png)

**Comment by radi-cho** [comment]
Facepalm. You can't replay after checkmate.
UPDATE: Fixed - https://github.com/RSG-Group/Chess/commit/73bab88fe2ea0b143e1082e24cfc7e46adf26043

**Comment by retrixe** [comment]
Does stalemate work?

**Comment by radi-cho** [comment]
no... ._.
