### ISSUE TITLE
Threefold repetition

### ISSUE THREAD

**Issue by radi-cho** [RSG-Group/Chess#5]
Add the [threefold repetition](https://en.wikipedia.org/wiki/Threefold_repetition) rule to the game.

**Comment by retrixe** [comment]
Yes please. Don't draw the game though, force AI to make a different move. Because the rook is just moving all the time. Until you capture it, of course.

**Comment by radi-cho** [comment]
I'll add the rule to the game logic, so it will be draw. The AI won't move the rook every time, after adding the minimax, you know I already work on it, so the both issues will be fixed soon.

UPDATE: It'll be added in #3

**Comment by radi-cho** [comment]
It'll be easier to find the threefold repetition if I add FEN notation support. Actually this notation doesn't provide info about the repetition, but we can compare the notations of the moves stored in object, for example `game.threefold`; Also this feature will be helpful in Chess APIs from the RSG Chess family.

More information: #7

**Comment by radi-cho** [comment]
I think It's done. The code is in #3 and there is a test pilot - https://rsg-chess-18836937.firebaseapp.com
