### ISSUE TITLE
Add FEN notation support.

### ISSUE THREAD

**Issue by radi-cho** [RSG-Group/Chess#7]
Add [FEN notation]() support.
This feature will be helpful:
* in RSG Chess APIs (The API will be more customizable and comfortable);
* in AI algorithm #3;
* when checking for the threefold repetition (#5);
* when checking for the fifty-move rule #6;

Needed fields:
- [x] Piece placement;
- [x] ~Active colour~;
- [x] ~Castling availability~;
- [x] ~En passant~;
- [ ] ~Halfmove clock~;
- [ ] ~Fullmove number~;

Additional to-dos:
- [ ] ~Separate the functions for more customizable API, more beautiful code and better performance~.
- [ ] ~Remove the useless FEN fields and move them to the Chess APIs - https://github.com/RSG-Group/Chess/issues/7#issuecomment-363340776~

**Comment by samet-karaibryamov** [comment]
Do you need "Active colour", "Castling availability", or "En passant"? I think only the piece placement is relevant for the threefold repetition rule.

**Comment by radi-cho** [comment]
@samet-karaibryamov - Yeah, we don't need "Active colour", "Castling availability", or "En passant" for the threefold rule, but they'll be helpful in the Chess APIs, I've planned.

**Comment by radi-cho** [comment]
With that in mind we can move this to the [Chess API](https://github.com/RSG-Group/RSG-Chess-API) repository and just use the position placement for the threefold repetition rule;
